apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  project: sonarqube
  source:
    repoURL: https://SonarSource.github.io/helm-chart-sonarqube
    targetRevision: "*.*.*"
    chart: sonarqube
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: sonarqube
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
