apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  project: sonarqube
  sources:
    - repoURL: https://SonarSource.github.io/helm-chart-sonarqube
      targetRevision: "*.*.*"
      chart: sonarqube
      helm:
        valueFiles:
          - $values/applications/sonarqube/values.yaml
    - repoURL: "https://github.com/castleking1810/infra-configuration.git"
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: sonarqube
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
