apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: prometheus
spec:
  project: prometheus-stack
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 48.3.6
    chart: kube-prometheus-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
