apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: prometheus
spec:
  project: prometheus-stack
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: "59.0.*"
      chart: kube-prometheus-stack
      helm:
        valueFiles:
          - $values/applications/prometheus/values.yaml
    - repoURL: "https://github.com/castleking1810/infra-configuration.git"
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
