apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: traefik
spec:
  project: traefik
  sources:
    - repoURL: https://traefik.github.io/charts
      targetRevision: "*.*.*"
      chart: traefik
      helm:
        valueFiles:
          - $values/applications/traefik/values.yaml
    - repoURL: "https://github.com/castleking1810/infra-configuration.git"
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
