apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: vault
spec:
  project: vault
  sources:
    - repoURL: https://helm.releases.hashicorp.com
      targetRevision: "0.28.*"
      chart: vault
      helm:
        valueFiles:
          - $values/applications/vault/values.yaml
    - repoURL: "https://github.com/ereldag/infra-configuration.git"
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
