apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: jenkins
spec:
  project: jenkins
  sources:
    - repoURL: https://charts.jenkins.io
      targetRevision: "5.1.*"
      chart: jenkins
      helm:
        valueFiles:
          - $values/applications/jenkins/values.yaml
    - repoURL: "https://github.com/ereldag/infra-configuration.git"
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
