apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: jenkins
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: deployment of jenkins

  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - "*"

  # allow applications to be deployed only to argocd and jenkins namespaces
  sourceNamespaces:
    - "argocd"
    - "jenkins"

  # Only permit applications to deploy to the jenkins and kube-system namespace in the same cluster
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
      name: in-cluster

  # enable cluster-scoped resources to be created
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  # enable all namespaced-scoped resources to be created
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: false
